kind: Pod
apiVersion: v1
metadata:
  name: fortune-pod
spec:
  containers:
   - image: navkkrnair/fortune:envvar
     imagePullPolicy: Always
     name: html-generator
     env:
      - name: INTERVAL
        valueFrom:
         configMapKeyRef:
           name: fortune-config-map
           key: sleep-interval
     volumeMounts:
      - name: html
        mountPath: /var/htdocs
   - image: nginx:alpine
     name: web-server
     ports:
      - containerPort: 80
        protocol: TCP
     volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly:  true
      - name: config
        mountPath: /etc/nginx/conf.d
        readOnly:  true  
  volumes:
   - name: html
     emptyDir:
        medium: Memory
   - name: config
     configMap:
       name: fortune-config-map      