kind: Pod
apiVersion: v1
metadata:
  name: fortune-pod
spec:
  containers:
   - image: navkkrnair/fortune:secret
     imagePullPolicy: Always
     name: html-generator
     env:
      - name: INTERVAL
        valueFrom:
         secretKeyRef:
           name: fortune-secret
           key: sleep-interval
     volumeMounts:
      - name: html
        mountPath: /var/htdocs
   - image: nginx:alpine
     imagePullPolicy: Always
     name: web-server
     ports:
      - containerPort: 80
      - containerPort: 443
        protocol: TCP
     volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly:  true
      - name: config
        mountPath: /etc/nginx/conf.d
        readOnly:  true
      - name: certs
        mountPath: /etc/nginx/certs
        readOnly:  true    
  volumes:
   - name: html
     emptyDir:
        medium: Memory
   - name: config
     configMap:
       name: fortune-config-map
       items:
        - key: my-nginx-config.conf
          path: gzip.conf
   - name: certs
     secret:
        secretName: fortune-secret
        
      