kind: Pod
apiVersion: v1
metadata:
  name: fortune
spec:
  containers:
   - image: navkkrnair/fortune:latest
     imagePullPolicy: Always
     name: html-generator
     volumeMounts:
      - name: html
        mountPath: /var/htdocs
   - image: nginx:alpine
     name: web-server
     ports:
      - containerPort: 80
        protocol: TCP
     volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly:  true
  volumes:
   - name: html
     #emptyDir: {}
     emptyDir:
        medium: Memory
      
