kind: Pod
apiVersion: v1
metadata:
  name: gitrepo-volume
spec:
  containers:
   - image: nginx:alpine
     name: web-server
     ports:
      - containerPort: 80
        protocol: TCP
     volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly:  true
  volumes:
   - name: html
     gitRepo:
        repository: https://github.com/navkkrnair/kubia-website-example.git
        revision: master
        directory: .
      
