kind: Pod
apiVersion: v1
metadata:
  name: mongodb-pod
spec:
  containers:
   - image: mongo
     name: mongodb
     ports:
      - containerPort: 27017
        protocol: TCP
     volumeMounts:
      - name: mongodb-data
        mountPath: /data/db
  volumes:
   - name: mongodb-data
     persistentVolumeClaim:
       claimName: mongodb-pvc