kind: Pod
apiVersion: v1
metadata:
  name: gce-disk
spec:
  containers:
   - image: mongo
     name: mongodb
     ports:
      - containerPort: 27017
        protocol: TCP
     volumeMounts:
      - name: mongo-data
        mountPath: /data/db
  volumes:
   - name: mongo-data
     gcePersistentDisk:
        pdName: mongodb
        fsType: ext4