kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
spec:
   storageClassName: ""  
   resources:
     requests:
       storage: 1Gi
   accessModes:
    - ReadWriteOnce
      