kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-with-storage-class
spec:
   storageClassName: fast-storage
   resources:
     requests:
       storage: 100Mi
   accessModes:
    - ReadWriteOnce    